import { env } from '@/env.mjs';

export const siteConfig = {
  title: 'Okwoli Godwin | Front-end | Mobile App software developer',
  description:
    "Hello, I'm Godwin. I am a front-end | Mobile App software developer from Lagos, Nigeria. I enjoy building sites and apps. My focus is React.",
  keywords: [
    'Okwoli Godwin',
    'Mobile developer',
    'Frontend developer',
    'Front-end software developer',
    'Nigeria',
    'React',
    'React native',
    'Next.js',
    'Web development',
    'Web design',
    'Front-end',
    'UI/UX',
    'Responsive design',
    'JavaScript',
    'TypeScript',
    'HTML',
    'CSS',
    'Portfolio',
    'Projects',
    'freelance front-end developer',
    'Website',
    'Web applications',
    'Developer',
    'Code',
    'Programming',
    'Tech enthusiast',
  ],
  url: env.SITE_URL || 'https://okwoligodwin.vercel.app/',
  googleSiteVerificationId: env.GOOGLE_SITE_VERIFICATION_ID || '',
};
